export CLICOLOR=1
export GREP_OPTIONS='--color=auto'
export LSCOLORS=excxcxdxgxegedabagacad
export PS1='\[\033[32m\]\u\[\033[00m\]@\[\033[34m\]\h\[\033[00m\]:\[\033[01;36m\]\w\[\033[00m\]\$ '

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

if [ -f $(brew --prefix)/Library/Contributions/brew_bash_completion.sh ]; then
  . $(brew --prefix)/Library/Contributions/brew_bash_completion.sh
fi
